### PR TITLE
"Snowball" masking with `snowblind`

### PR DESCRIPTION
**Pull request by gbrammer**
Implement DQ masking with the [snowblind](https://github.com/mpi-astronomy/snowblind) module, which has better mask shapes that vary in size depending on the snowball intensity.

As of 5 Dec 2023, the functionality to run the masking on `rate` products has not yet been merged into the main `snowblind` repository, so it has to be installed from the fork:

```bash
pip install git+https://github.com/gbrammer/snowblind.git
```
snowblind

### CODE REVIEW

**Comment by gbrammer** [comment]
h/t @jdavies-st

**Comment by pascaloesch** [comment]
Note that snowblind requires scikit-image>=0.20.0, where 'skimage.morphology.isotropic_dilation' was introduced.

**Comment by gbrammer** [comment]
> ```python
> snowblind_kws = dict(new_jump_flag=1024, min_radius=4, growth_factor=1.5, unset_first=True)
> ```

Added in 93deb61068d36b01792a372a995516b2606250ae.  Thanks!

**Comment by gbrammer** [comment]
> Note that snowblind requires scikit-image>=0.20.0, where 'skimage.morphology.isotropic_dilation' was introduced.

Added in 93deb61068d36b01792a372a995516b2606250ae.  Thanks!

**Comment by jdavies-st** [comment]
> Note that snowblind requires scikit-image>=0.20.0, where 'skimage.morphology.isotropic_dilation' was introduced.

Thanks for noting this @pascaloesch.  I'll update the requirements for `snowblind` and release.

**Comment by jdavies-st** [comment]
`snowblind 0.2.1` is now released with the updated functionality for working with _rate and _rateints files, and also with the updated `scikit-image` version requirement.  Thanks!  👍

**Comment by gbrammer** [comment]
> `snowblind 0.2.1` is now released with the updated functionality for working with _rate and _rateints files, and also with the updated `scikit-image` version requirement. Thanks! 👍

Awesome, thanks!

**Pull request merged**
