### PR TITLE
Switch from PeakUtils to Scipy.Signal

### PR DESCRIPTION
**Pull request by TheSkyentist**
Fix addressing #235.

### CODE REVIEW

**Comment by gbrammer** [comment]
Thanks, looks pretty straightforward.  It looks like you figured out the mapping between the two modules with the thresholding.  Rather than overloading the `height=` keyword with some array transformations, could you consider writing a function (and a test) like `utils.threshold_peak_indexes` or something that takes "threshold" and "min_separation" keywords and behaves like `peakutils.indexes`?

**Comment by TheSkyentist** [comment]
I'd be willing to do this, but perhaps this would be quite a short function in utils. Perhaps I can clean up the creation of the height value to make it clearer. Let me make some changes and let me know if they make things more readable or if you'd prefer to make a new function.

**Comment by gbrammer** [comment]
There's nothing wrong with a short function!  Just to make the behavior explicit and easily testable.

**Comment by TheSkyentist** [comment]
Okay I'll refactor in a bit.
Also a note that the CI is failing because the latest photutils fails with
the latest drizzlepac (as of 3 hours ago). Drizzlepac has changes in place
for their next release, but for now we might want to pin photutils as well.

**Comment by gbrammer** [comment]
OK, this looks great.  Can you add a test to `grizli/tests/test_utils.py` for the new function?  The test doesn't have to be super comprehensive, just something that verifies that the function works as expected given `numpy`, `scipy`, etc.

**Review by gbrammer — APPROVED** [review]
Looks good!

**Pull request merged**
